// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// make_initial
List make_initial(arma::vec Y, arma::vec S, arma::mat Z, arma::mat X);
RcppExport SEXP _MRIE_make_initial(SEXP YSEXP, SEXP SSEXP, SEXP ZSEXP, SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(make_initial(Y, S, Z, X));
    return rcpp_result_gen;
END_RCPP
}
// MR_estimation_NoMissing_CORR
List MR_estimation_NoMissing_CORR(arma::mat X, arma::vec Y, arma::mat Z, arma::vec S, arma::vec alpha_init, arma::vec beta_init, double gamma_init, double sigmaSsquare_init, double sigmaYsquare_init, double rho_init, double epsilon);
RcppExport SEXP _MRIE_MR_estimation_NoMissing_CORR(SEXP XSEXP, SEXP YSEXP, SEXP ZSEXP, SEXP SSEXP, SEXP alpha_initSEXP, SEXP beta_initSEXP, SEXP gamma_initSEXP, SEXP sigmaSsquare_initSEXP, SEXP sigmaYsquare_initSEXP, SEXP rho_initSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha_init(alpha_initSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_init(beta_initSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_init(gamma_initSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaSsquare_init(sigmaSsquare_initSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaYsquare_init(sigmaYsquare_initSEXP);
    Rcpp::traits::input_parameter< double >::type rho_init(rho_initSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(MR_estimation_NoMissing_CORR(X, Y, Z, S, alpha_init, beta_init, gamma_init, sigmaSsquare_init, sigmaYsquare_init, rho_init, epsilon));
    return rcpp_result_gen;
END_RCPP
}
// MR_estimation_rho
List MR_estimation_rho(arma::vec Y, arma::vec S, arma::vec R, arma::mat Z, arma::mat X, arma::vec alpha_init, arma::vec beta_init, double gamma_init, double sigmaSsquare_init, double sigmaYsquare_init, double rho_init, double epsilon);
RcppExport SEXP _MRIE_MR_estimation_rho(SEXP YSEXP, SEXP SSEXP, SEXP RSEXP, SEXP ZSEXP, SEXP XSEXP, SEXP alpha_initSEXP, SEXP beta_initSEXP, SEXP gamma_initSEXP, SEXP sigmaSsquare_initSEXP, SEXP sigmaYsquare_initSEXP, SEXP rho_initSEXP, SEXP epsilonSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< arma::vec >::type Y(YSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type S(SSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type R(RSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type Z(ZSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type alpha_init(alpha_initSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type beta_init(beta_initSEXP);
    Rcpp::traits::input_parameter< double >::type gamma_init(gamma_initSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaSsquare_init(sigmaSsquare_initSEXP);
    Rcpp::traits::input_parameter< double >::type sigmaYsquare_init(sigmaYsquare_initSEXP);
    Rcpp::traits::input_parameter< double >::type rho_init(rho_initSEXP);
    Rcpp::traits::input_parameter< double >::type epsilon(epsilonSEXP);
    rcpp_result_gen = Rcpp::wrap(MR_estimation_rho(Y, S, R, Z, X, alpha_init, beta_init, gamma_init, sigmaSsquare_init, sigmaYsquare_init, rho_init, epsilon));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_MRIE_make_initial", (DL_FUNC) &_MRIE_make_initial, 4},
    {"_MRIE_MR_estimation_NoMissing_CORR", (DL_FUNC) &_MRIE_MR_estimation_NoMissing_CORR, 11},
    {"_MRIE_MR_estimation_rho", (DL_FUNC) &_MRIE_MR_estimation_rho, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_MRIE(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
