# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

make_initial <- function(Y, S, Z, X) {
    .Call('_MRIE_make_initial', PACKAGE = 'MRIE', Y, S, Z, X)
}

MR_estimation_NoMissing_CORR <- function(X, Y, Z, S, alpha_init, beta_init, gamma_init, sigmaSsquare_init, sigmaYsquare_init, rho_init, epsilon) {
    .Call('_MRIE_MR_estimation_NoMissing_CORR', PACKAGE = 'MRIE', X, Y, Z, S, alpha_init, beta_init, gamma_init, sigmaSsquare_init, sigmaYsquare_init, rho_init, epsilon)
}

MR_estimation_rho <- function(Y, S, R, Z, X, alpha_init, beta_init, gamma_init, sigmaSsquare_init, sigmaYsquare_init, rho_init, epsilon) {
    .Call('_MRIE_MR_estimation_rho', PACKAGE = 'MRIE', Y, S, R, Z, X, alpha_init, beta_init, gamma_init, sigmaSsquare_init, sigmaYsquare_init, rho_init, epsilon)
}

